Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = os.path.join(str(Dir('#')), 'Weather')

src = Glob('*.c')

CPPPATH = [cwd, str(Dir('#'))]
group = DefineGroup('Weather', src, depend = ['PKG_USING_WEBCLIENT'], CPPPATH = CPPPATH)
Return('group')
