import os
from building import * 

# get current dir path
cwd = GetCurrentDir()
inc = [cwd]
src = Glob('*.c')

# add group to IDE project
group = DefineGroup('NRF-APP', src, depend = ['NRF24L01_USING_GATEWAY'], CPPPATH = inc)

Return('group')