import os
from building import * 

# get current dir path
cwd = GetCurrentDir()
inc = [cwd]
src = Glob('*.c')

# add group to IDE project
group = DefineGroup('RFICHelper', src, depend = ['RT_USING_ICCARD'], CPPPATH = inc)

Return('group')