Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'applications')

src = Split("""
main.c
delay.c
rfic-manage.c
app_uart.c
gpio_oper.c
pcf8563.c
""")

CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
