Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = os.path.join(str(Dir('#')), 'QRCodeScan')

src = Glob('*.c')

CPPPATH = [cwd, str(Dir('#'))]
group = DefineGroup('QRCodeScan', src, depend = [], CPPPATH = CPPPATH)
Return('group')
